### PR TITLE
docs: add NetBSD instructions

### PR DESCRIPTION
**Pull request by 0323pin**
CommitLog for your reference, http://mail-index.netbsd.org/pkgsrc-changes/2024/05/18/msg300410.html

### CODE REVIEW

**Review by orhun — APPROVED** [review]
Lovely, thanks!

**Comment by 0323pin** [comment]
> Lovely, thanks!

Thanks! Really nice tool 👍

**Comment by orhun** [comment]
Awesome, done in 557dfa16fae3e02c5972a79bc7de6c8c028b3083

**Comment by 0323pin** [comment]
Cool, thanks!

I'll try to remember to add the logo to the package on the next update.

**Pull request merged**
